# The main configuration file.
# Usable standalone for a fully functioning site
# or as base values for all other configurations.

# To use run `hugo` or `hugo server` from the `exampleSite` directory

# change this to a value appropriate for you; if your site is served from a subdirectory
# set it like 'https://example.com/mysite/'
baseURL = 'https://alirea.top/'

# 需要设置为 'true' 才能从 Web 服务器和文件系统提供此页面;
# 如果你将此值设置为 'true'，则 'baseURL' 不能包含子目录;
# 如果你不想从文件系统中提供你的页面，你也可以设置这个值
# 改为 'false'
relativeURLs = false # true -> rewrite all site-relative URLs (those with a leading slash) to be relative to the current content


# yeah, well, obviously a mandatory setting for your site, if you want to
# use this theme ;-)
theme = 'hugo-theme-relearn'

defaultContentLanguage = 'cn'
# if you want to get rrrid o' ourrr pirrrates nonsense uncomment th' next line
# disableLanguages = ['pir']
# feel free to delete all files and directories related to this translation:
# - `content/pir/`
# - `i18n/`
# - `layouts/partials/shortcodes/piratify.html`
# - `layouts/partials/toc.html`
# - `layouts/shortcodes/piratify.html`

# add showcase-specific output formats
[outputs]
  # `print` - activate the themes feature to print whole chapters or leaf pages
  home = ['html', 'rss', 'print']
