# showcase of the menu shortcuts;
# you can use relative URLs linking to your content or use
# fully-qualified URLs to link outside of your project

[zh-CN]
  title = 'AlireaLibrary'
  weight = 1
  languageCode = 'zh-CN'
  languageName = '中文'
  languageDirection = 'ltr'
  # Language dependent settings:
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
  contentDir = 'content'
  [zh-CN.params]
    landingPageName = '主页'

[[zh-CN.menu.shortcuts]]
  pre = '<i class="fa-fw fas fa-puzzle-piece"></i> '
  name = 'Github仓库'
  url = 'https://github.com/Alirea10/Hugo-AlireaLibrary'
  weight = 1
[[zh-CN.menu.shortcuts]]
  pre = '<i class="fa-fw fab fa-github"></i> '
  name = 'Github Web仓库'
  url = 'https://github.com/Alirea10/Hugo-AlireaLibraryWeb'
  weight = 2
